[SELC-4598] feat: Added V2 for getUserProductDetails api
pagopa/selfcare-external-api-backend pull request #213
Opened 2024-04-11 09:02 UTC by KevinSi96

#### List of Changes

Added V2 version of user's onboarded product retrieval api

#### Motivation and Context

Migrate the api to use the new user-ms instead of ms-core

#### How Has This Been Tested?

Locally deployed and tested

#### Screenshots (if appropriate):

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-04-11 12:29 UTC, pierpaolodidato89 commented on connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/UserMsConnectorImpl.java
> +    public List<UserInstitution> getUsersInstitutions(String userId, String institutionId, Integer page, Integer size, List<String> productRoles, List<String> products, List<PartyRole> roles, List<St
Maybe we could wrap all these params into an object to make the method more readable.

2024-04-11 12:30 UTC, pierpaolodidato89 commented on connector/rest/src/main/java/it/pagopa/selfcare/external_api/connector/rest/UserMsConnectorImpl.java
> +            return null;
Could we avoid the else statement and return the empty collection directly?

2024-04-12 08:27 UTC, manuraf requested changes

2024-04-12 08:27 UTC, manuraf commented on web/src/main/java/it/pagopa/selfcare/external_api/web/controller/UserV2Controller.java
> +    @ApiOperation(value = "", notes = "${swagger.external_api.user.api.getUserProductInfo}")
you could add `nickname` for setting an appropriate operationId...for ex: `getUserOnboardedProductUsingGET`

2024-04-12 09:29 UTC, manuraf approved these changes

2024-04-12 09:35 UTC, merged